### ISSUE TITLE
Plans for releasing the code?

### ISSUE THREAD

**Issue by Water-Silver** [barisgecer/OSTeC#1]
Hi!
Loved your work.
Any plans for releasing the code?

Thanks

**Comment by barisgecer** [comment]
I will release the code as soon as possible

**Comment by zwzhang123** [comment]
waiting...

**Comment by barisgecer** [comment]
@zwzhang121 I am very sorry, I am adapting it to a public 3d reconstruction code as the original 3d reconstruction code has been commercialized. Also, I was on summer holiday, will try to push it ASAP from now on.

**Comment by qiuyu96** [comment]
I also keep waiting for the code...

**Comment by Michaelwhite34** [comment]
Anytime  soon ?

**Comment by barisgecer** [comment]
I am sorry everyone, please bear with me. I am working full-time and trying to find some time to replace the reconstruction code with some public one. I will try to finish it ASAP.

**Comment by jacquelinelala** [comment]
Still waiting...

**Comment by barisgecer** [comment]
Well, after a long time finally it is out! Sorry for the delay
