### ISSUE TITLE
help: exporting mesh?

### ISSUE THREAD

**Issue by knoopx** [barisgecer/OSTeC#12]
Hello, I tried to capture the trimesh generated by `Operator#run`:

```python
face = self.get_tmesh(im, reconstruction_dict)
results_dict['face'] = face
```

and then export it using menpo3d io: 

```python
import menpo3d.io as m3dio
...
m3dio.export_textured_mesh(results_dict["face"].tmesh, save_path.replace(ext, ".obj"), extension="obj", overwrite=True)
```
but the generated mesh is corrupt:

![image](https://user-images.githubusercontent.com/100993/154302970-e7afc80b-0fb8-4ad6-8df5-655329ffe6d0.png)

any idea why? is there a proper way to do so? tried using original code from [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch) and the mesh is ok but it fails to generate texture due tensor size missmatch.

**Comment by laolongboy** [comment]
I had the same problem while trying to use original code from Deep3DFaceRecon_pytorch.

```
RuntimeError: The size of tensor a (35709) must match the size of tensor b (53215) at non-singleton dimension 1
```

**Comment by barisgecer** [comment]
In the latest commit, I replaced the topology with full-face topology. Thus this problem should be fixed. Can you try again?

And please use my forked repo for [Deep3DFaceRecon_pytorch](https://github.com/barisgecer/Deep3DFaceRecon_pytorch)

**Comment by barisgecer** [comment]
I believe this issue has now been solved. Please re-open if it is not.
