### ISSUE TITLE
how to generate obj file?

### ISSUE THREAD

**Issue by tianyu06030020** [barisgecer/OSTeC#14]
I want to observe the reconstructed performance in meshlab or blender, please give me a tip how to generate the obj file, thank a lot.

**Comment by AyushP123** [comment]
Hi, 
Can you share how did you save the texture and obj file? I am able to just save the mesh and the texture separately but am not able to save a textured mesh.

**Comment by tianyu06030020** [comment]
> 
 Hi AyushP123,
I'm not sure whether you met the same problem as me, I want to observe the 3d reconstruction so this is my solution as follows:

1、generate the obj file with vt coordinate. (be attention: the minimum of  the face index in obj file must 1)
2、generate the uv map.
3、observe the performance through mtl file

**Comment by laolongboy** [comment]
> 

Hi, can you share your code exporting the obj file. I have tried using menpo3d.io.output.base.export_textured_mesh. But the results are not correct.

**Comment by tianyu06030020** [comment]
> > 
> 
> Hi, can you share your code exporting the obj file. I have tried using menpo3d.io.output.base.export_textured_mesh. But the results are not correct.

Hi， laolongboy

the only difference with #12 is that I add the tmesh.trilist by 1:

import menpo3d.io as m3dio
results_dict['face'].tmesh.trilist += 1
m3dio.export_textured_mesh(results_dict['face'].tmesh, save_path.replace(ext, ".obj"),
                                               extension="obj", overwrite=True)

**Comment by laolongboy** [comment]
> > > 
> > 
> > 
> > Hi, can you share your code exporting the obj file. I have tried using menpo3d.io.output.base.export_textured_mesh. But the results are not correct.
> 
> Hi， laolongboy
> 
> the only difference with #12 is that I add the tmesh.trilist by 1:
> 
> import menpo3d.io as m3dio results_dict['face'].tmesh.trilist += 1 m3dio.export_textured_mesh(results_dict['face'].tmesh, save_path.replace(ext, ".obj"), extension="obj", overwrite=True)

Thanks. It works.

![image](https://user-images.githubusercontent.com/25175047/158949217-5403670f-3612-4759-b268-acbb407190ff.png)

The saved .obj file includes the texture coordinates. How can I display the texture in MeshLab?

**Comment by tianyu06030020** [comment]
> 

the origin output has uv_map, you can write a mtl file which can connect with obj and uv_map, 
mtl point out the uv_map and obj point out the mtl file,  then you will see the mesh with texture

**Comment by manifoldhiker** [comment]
Could somebody explain why `tmesh.trilist += 1` works? Thank you in advance 🚀

**Comment by barisgecer** [comment]
In the latest commit, I wrote an export script at the end of run_ostec.py. So just running it should give you obj files with tcoords and texture maps, thus can be viewed directly on MeshLab etc.

**Comment by zenonLEE** [comment]
> > 
> 
> the origin output has uv_map, you can write a mtl file which can connect with obj and uv_map, mtl point out the uv_map and obj point out the mtl file, then you will see the mesh with texture

Hi, can you share your code exporting the mtl file with uv map and obj file. Thank you in advance!
