### ISSUE TITLE
How to obtain the visibility mask of the raw face image

### ISSUE THREAD

**Issue by HarshWinterBytes** [barisgecer/OSTeC#15]
Thank you very much for sharing such excellent work. I want to know how to obtain the visibility mask of the raw face image.  Thank you again! Looking forward to your reply!

**Comment by barisgecer** [comment]
Hi,

I am basically calculating the angle between the camera and the surface normals ([here](https://github.com/barisgecer/OSTeC/blob/6838b9f8c0054275abada6260025c7e1bfe38f31/core/operator.py#L306)), if it is less than 0.6*(pi/2), I assume it is visible by thresholding the angles in UV space ( [here](https://github.com/barisgecer/OSTeC/blob/6838b9f8c0054275abada6260025c7e1bfe38f31/core/operator.py#L312) ).

Hope this helps,
Baris

**Comment by HarshWinterBytes** [comment]
Thank you for your reply!
