### ISSUE TITLE
How to render correctly?

### ISSUE THREAD

**Issue by laolongboy** [barisgecer/OSTeC#16]
input:
![ffhq](https://user-images.githubusercontent.com/25175047/159427313-c38d534c-64c7-420d-9fef-b5b38de044c9.png)

render results after reconstruction:
![ffhq_render_angle_0](https://user-images.githubusercontent.com/25175047/159427378-0efe87b0-b7c9-4c66-8b05-9768e9cbb420.jpg)
![ffhq_render_angle_45](https://user-images.githubusercontent.com/25175047/159427390-3a8d4788-f6f1-465e-848d-947c01a40eab.jpg)

code:
```
# fitting
fitting = deep3dmodel.recontruct(im_menpo2PIL(img), lms, test=False)

# Prepare Textured Trimesh with visible part of the face
face = operator.get_tmesh(im, fitting)

# Render to specific angle
from utils.image_rasterization import rasterize_image

im, _ = rasterize_image(face.tmesh, operator.img_shape, pose_angle_deg=[0, 0, 0], cam_dist=4.5)
cv2.imwrite(f'./split_test/ffhq_render_angle_0.jpg', np.array(im_menpo2PIL(im))[:, :, ::-1])

im, _ = rasterize_image(face.tmesh, operator.img_shape, pose_angle_deg=[0, 45, 0], cam_dist=4.5)
cv2.imwrite(f'./split_test/ffhq_render_angle_45.jpg', np.array(im_menpo2PIL(im))[:, :, ::-1])
```

**Comment by barisgecer** [comment]
In the latest commit, I replaced the topology with full-face topology. Thus this problem should be fixed. Can you try again?

**Comment by laolongboy** [comment]
> 

I found out that the problem is the index of 'trilist'. The trilist for `face.tmesh` starts at -1. Adding 1 before rendering gives the correct result.
```
def create_syn(self, face, trg_angle=[0, 0, 0], include_mask=None):
        view_angle_trg = self.camera_tri_angle(face.tmesh, pose_angle_deg=trg_angle)
        mesh_cp = face.tmesh.copy()
        mesh_cp.trilist = mesh_cp.trilist + 1
        im, projected_mesh = rasterize_image(mesh_cp, self.img_shape, pose_angle_deg=trg_angle, cam_dist=4.5)
```

**Comment by barisgecer** [comment]
Thanks, that is weird. Not sure what causes this. Nevertheless, with the latest version (as far as I checked) this shouldn't be an issue if you follow my export script.
