### ISSUE TITLE
Unable to reproduce paper results

### ISSUE THREAD

**Issue by bosmart** [barisgecer/OSTeC#17]
As per the subject line; tried to frontalize the photo of Christopher Lee (top left input in Fig.1), the result looks nothing like yours for some reason...

**Comment by barisgecer** [comment]
I will have a look, could you share your result in the meantime?

**Comment by bosmart** [comment]
Input:
![image](https://user-images.githubusercontent.com/5089507/163882015-0b9ab55b-3e35-4c4f-a8a5-81b139d54625.png)

After frontalization:
![image](https://user-images.githubusercontent.com/5089507/163882048-7e6ad9fc-5d68-4b84-a853-1cc2dc350023.png)

**Comment by barisgecer** [comment]
Hi, thanks for pointing out this problem. I have been working on it a bit and found a series of bug that are triggered by the latest changes I have made in the topology.

As of the commit https://github.com/barisgecer/OSTeC/commit/5f3fa5498d0db956075a30bfde6641861b0c1c6e , this problem should be solved. I am having the following results now:
![chris_frontal](https://user-images.githubusercontent.com/2118077/166150241-69f6a4e3-d4db-44c5-bf3e-d84f6252ee2f.png)

![chris](https://user-images.githubusercontent.com/2118077/166150231-b91f4130-eb04-43e5-aea7-2572bad03932.png)

Pretty close to the ones in the paper, but please note that the paper was using GANFit for face reconstruction which is not publicly available. 

Hope this helps, let me know if you have any more questions. Cheers,
Baris
