### ISSUE TITLE
I would like to know how to get the de-occluded frontal face image

### ISSUE THREAD

**Issue by Yangleyang** [barisgecer/OSTeC#20]
Thanks for your great work。
I would like to know how to get the de-occluded frontal face image.
I input the occlusion image, and finally got the obj file and uv map. But there is no picture after de-occlusion

**Comment by barisgecer** [comment]
Hi, sorry that it wasn't explained clearly in README.md. You need to pass -f argument to obtain frontalized image.
Hope this helps,
Baris

**Comment by Yangleyang** [comment]
> 嗨，很抱歉，README.md 中没有解释清楚。您需要通过 -f 参数来获取正面图像。 希望这会有所帮助， 巴里斯



> Hi, sorry that it wasn't explained clearly in README.md. You need to pass -f argument to obtain frontalized image. Hope this helps, Baris

Thank you very much for your guidance
