### ISSUE TITLE
how can you get the complete uv

### ISSUE THREAD

**Issue by madgnot** [barisgecer/OSTeC#3]

**Comment by madgnot** [comment]
i have a  question about your dataset, how can you get the complete uv map ,in your paper you just said you reconstruction it from the 2d face dataset

**Comment by barisgecer** [comment]
Well, we complete the UVs by a novel approach that we thoroughly explain in the paper. Please have a look at the paper: https://openaccess.thecvf.com/content/CVPR2021/papers/Gecer_OSTeC_One-Shot_Texture_Completion_CVPR_2021_paper.pdf
