### ISSUE TITLE
Will it generate high quality texture on high resolution photo ?

### ISSUE THREAD

**Issue by Michaelwhite34** [barisgecer/OSTeC#4]
I haven't tested it,will it preserve high resolution detail of photos in generated textures (like 5000*5000)?

**Comment by barisgecer** [comment]
The quality relies on the input image (for the visible part) and StyleGAN generations (which is 1024x1024) when the 'soft' mode is activated. In 'hard' mode, they are all in StyleGAN resolution. Please see [here](https://github.com/barisgecer/OSTeC/blob/main/README.md#usage) about modes
