### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by loboere** [barisgecer/OSTeC#7]
active conda and all that
when I install everything and proceed to run the script

python run_ostec.py --source_dir [source_dir] --save_dir [save_dir] [-f] -i [iterations (default 200)] -m [soft | hard | auto]

first error
```
Traceback (most recent call last):
  File "run_ostec.py", line 12, in <module>
    import menpo.io as mio
ModuleNotFoundError: No module named 'menpo'

```

  then! pip install menpo

then another mistake

```

/usr/local/lib/python3.7/site-packages/menpo/image/base.py:25: UserWarning: Falling back to scipy interpolation for affine warps
  warn("Falling back to scipy interpolation for affine warps")
Traceback (most recent call last):
  File "run_ostec.py", line 17, in <module>
    from core.operator import Operator
  File "/content/OSTeC/core/operator.py", line 7, in <module>
    from core.projection_handler import Projection_Handler
  File "/content/OSTeC/core/projection_handler.py", line 13, in <module>
    import external.stylegan2.dnnlib.tflib as tflib
  File "/content/OSTeC/external/stylegan2/dnnlib/tflib/__init__.py", line 7, in <module>
    from . import autosummary
  File "/content/OSTeC/external/stylegan2/dnnlib/tflib/autosummary.py", line 26, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

which version of tensorflow should I install

It seems that Conda did not install some things so I installed it myself but now it throws this error

```
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
/usr/local/lib/python3.7/site-packages/kornia/augmentation/augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
Traceback (most recent call last):
  File "/content/OSTeC/run_ostec.py", line 74, in <module>
    main(args)
  File "/content/OSTeC/run_ostec.py", line 27, in main
    operator = Operator(args)
  File "/content/OSTeC/core/operator.py", line 94, in __init__
    self.tcoords_full = mio.import_pickle('models/topology/tcoords_full.pkl')
  File "/usr/local/lib/python3.7/site-packages/menpo/io/input/base.py", line 484, in import_pickle
    return _import(filepath, pickle_types, importer_kwargs=kwargs)
  File "/usr/local/lib/python3.7/site-packages/menpo/io/input/base.py", line 912, in _import
    raise ValueError("{} is not a file".format(path))
ValueError: /content/OSTeC/external/deep3dfacerecon/models/topology/tcoords_full.pkl is not a file
```

**Comment by AlonsoJAG** [comment]
You have to change your python 3.7 version to python 3.5.
conda install python=3.5. It worked to me.

**Comment by AlonsoJAG** [comment]
> active conda and all that when I install everything and proceed to run the script
> 
> python run_ostec.py --source_dir [source_dir] --save_dir [save_dir] [-f] -i [iterations (default 200)] -m [soft | hard | auto]
> 
> first error
> 
> ```
> Traceback (most recent call last):
>   File "run_ostec.py", line 12, in <module>
>     import menpo.io as mio
> ModuleNotFoundError: No module named 'menpo'
> ```
> 
> then! pip install menpo
> 
> then another mistake
> 
> ```
> 
> /usr/local/lib/python3.7/site-packages/menpo/image/base.py:25: UserWarning: Falling back to scipy interpolation for affine warps
>   warn("Falling back to scipy interpolation for affine warps")
> Traceback (most recent call last):
>   File "run_ostec.py", line 17, in <module>
>     from core.operator import Operator
>   File "/content/OSTeC/core/operator.py", line 7, in <module>
>     from core.projection_handler import Projection_Handler
>   File "/content/OSTeC/core/projection_handler.py", line 13, in <module>
>     import external.stylegan2.dnnlib.tflib as tflib
>   File "/content/OSTeC/external/stylegan2/dnnlib/tflib/__init__.py", line 7, in <module>
>     from . import autosummary
>   File "/content/OSTeC/external/stylegan2/dnnlib/tflib/autosummary.py", line 26, in <module>
>     import tensorflow as tf
> ModuleNotFoundError: No module named 'tensorflow'
> ```
> 
> which version of tensorflow should I install
> 
> It seems that Conda did not install some things so I installed it myself but now it throws this error
> 
> ```
> /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> Using TensorFlow backend.
> /usr/local/lib/python3.7/site-packages/kornia/augmentation/augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
>   category=DeprecationWarning,
> Traceback (most recent call last):
>   File "/content/OSTeC/run_ostec.py", line 74, in <module>
>     main(args)
>   File "/content/OSTeC/run_ostec.py", line 27, in main
>     operator = Operator(args)
>   File "/content/OSTeC/core/operator.py", line 94, in __init__
>     self.tcoords_full = mio.import_pickle('models/topology/tcoords_full.pkl')
>   File "/usr/local/lib/python3.7/site-packages/menpo/io/input/base.py", line 484, in import_pickle
>     return _import(filepath, pickle_types, importer_kwargs=kwargs)
>   File "/usr/local/lib/python3.7/site-packages/menpo/io/input/base.py", line 912, in _import
>     raise ValueError("{} is not a file".format(path))
> ValueError: /content/OSTeC/external/deep3dfacerecon/models/topology/tcoords_full.pkl is not a file
> ```

You have to change your python 3.7 version to python 3.5.
conda install python=3.5. It worked to me.

**Comment by AlonsoJAG** [comment]
Hi, when I want to run ostec:

python run_ostec.py --source_dir figures\input\test21_out.jpg --save_dir figures\output -i 200 -m soft

I have the following error message.

Traceback (most recent call last):
  File "run_ostec.py", line 17, in <module>
    from core.operator import Operator
  File "D:\Desarrollos\OSTeC\core\operator.py", line 7, in <module>
    from core.projection_handler import Projection_Handler
  File "D:\Desarrollos\OSTeC\core\projection_handler.py", line 105
    dl = np.expand_dims(np.load(os.path.join(self.args.load_last, f'{name}.npy')), axis=0)                                                                              ^
SyntaxError: invalid syntax

Please, how can I fix it?

Thanks

**Comment by barisgecer** [comment]
Hi @loboere,

I tried to rebuild the environment on a different machine. I haven't encountered any problem with menpo and tensorflow installation as they are in the enviroment.yml file. Nevertheless they are not a big issue anyway. Please see the following links referencing menpo and tensorflow in enviroment.yml file:
- https://github.com/barisgecer/OSTeC/blob/7c73bb0164f4b834463333c5eb148de6de8a727f/environment.yml#L106
- https://github.com/barisgecer/OSTeC/blob/7c73bb0164f4b834463333c5eb148de6de8a727f/environment.yml#L208

For the other error you are getting. The 'tcoords_full,pkl' file is here https://github.com/barisgecer/OSTeC/blob/main/models/topology/tcoords_full.pkl
Meaning that it should be seeked right under 'OSTeC/models/topology/tcoords_full.pkl'. In your case it is seeked under 'deep3dfacerecon' dir. This sounds like your PYTHONPATH (or the dir you are calling run_ostec script) is set to 'OSTeC/external/deep3dfacerecon/'. Please try to set the basedir to 'OSTeC/' and try again.
